name: Sync Project Status with Assignees

on:
  issues:
    types: [assigned, unassigned]

permissions:
  issues: read

jobs:
  status-update-call:
    uses: ./.github/workflows/status-update-call.yml
    with:
      issue_number: ${{ github.event.issue.number }}
      action: ${{ github.event.action }}
    secrets:
      PJ_APP_ID: ${{ secrets.PJ_APP_ID }}
      PJ_APP_PEM: ${{ secrets.PJ_APP_PEM }}
